# Generated by Django 4.2.7 on 2023-11-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_alter_examplemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
