# Generated by Django 4.2.7 on 2023-11-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_alter_examplemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='id',
            field=models.UUIDField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
