# Generated by Django 4.2.7 on 2023-11-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_number', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationNumberModel',
            fields=[
                ('id', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
                ('rent_expires_at_timestamp', models.DateTimeField(verbose_name='Время аренды номера')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='countermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='countermodel',
            name='id',
            field=models.UUIDField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
