# Generated by Django 4.2.7 on 2023-11-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_number', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationNumberModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
                ('rent_expires_at_timestamp', models.DateTimeField(verbose_name='Время аренды номера')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
