# Generated by Django 4.2.7 on 2023-11-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifeCaseModel',
            fields=[
                ('id', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(max_length=64, verbose_name='Регистрационный номер ПЖИ')),
                ('cito', models.BooleanField(verbose_name='Срочность')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
